# Jekyll configuration for docs

ofTitle: OpenFrontend.Framework
ofDescription: OpenFrontend is a multipurpose theme, crafted for all the touristic websites like  destinations, transport companies, hotels or associations.