parameters:
    openfrontend.manifest_json_path: '%sculpin.project_dir%/docs/assets/open-frontend/manifest.json'

sculpin:
    source_dir: '%sculpin.project_dir%/docs'
    permalink: pretty

sculpin_content_types:
    posts:
        enabled: false

    components:
        type: path
        path: _data_provider/components
        singular_name: component
        layout: default
        enabled: true
        permalink: component/:title

    layout:
        type: path
        path: _data_provider/layout
        singular_name: layout
        layout: default
        enabled: true
        permalink: layout/:title

    plugins:
        type: path
        path: _data_provider/plugins
        singular_name: plugin
        layout: default
        enabled: true
        permalink: plugin/:title

    snippets:
        type: path
        path: _data_provider/snippets
        singular_name: snippet
        layout: default
        enabled: true
        permalink: snippet/:title