services:
    listener.rebuild_on_assets_change:
        class: OpenFrontendDocsBundle\EventListener\RebuildOnAssetsChangeListener
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.asset:
        class: OpenFrontendDocsBundle\Twig\AssetExtension
        arguments:
            - '%openfrontend.manifest_json_path%'
        tags:
            - { name: twig.extension }

    twig.extension.data_provider:
        class: OpenFrontendDocsBundle\Twig\DataProviderExtension
        arguments:
            - '@sculpin.data_provider_manager'
        tags:
            - { name: twig.extension }

    twig.extension.short_uid:
        class: OpenFrontendDocsBundle\Twig\ShortUidExtension
        tags:
            - { name: twig.extension }

    twig.extension.string_loader:
        class: Twig\Extension\StringLoaderExtension
        tags:
            - { name: twig.extension }