services:
    twig.extension.asset:
        class: OpenFrontendDocsBundle\Twig\AssetExtension
        arguments:
            - '%openfrontend.manifest_json_path%'
        tags:
            - { name: twig.extension }

    twig.extension.data_provider:
        class: OpenFrontendDocsBundle\Twig\DataProviderExtension
        arguments:
            - '@sculpin.data_provider_manager'
        tags:
            - { name: twig.extension }

    twig.extension.short_uid:
        class: OpenFrontendDocsBundle\Twig\ShortUidExtension
        tags:
            - { name: twig.extension }

    twig.extension.html_example:
        class: OpenFrontendDocsBundle\Twig\HtmlExampleExtension
        arguments:
            - '@sculpin_twig.twig'
        tags:
            - { name: twig.extension }