name: Cleanup server on branch delete

on: delete

jobs:
    cleanup:
        if: github.event.ref_type == 'branch'
        name: Cleanup server on branch delete
        runs-on: ubuntu-latest
        steps:
            - name: Set environment variables based on branch
              env:
                GITHUB_REF_NAME: ${{ github.ref_name }}
              run: |
                CLEANED_BRANCH_NAME=${GITHUB_REF_NAME//\//-}
                echo "TARGET_PATH=/var/www/vhosts/openfrontend.tourismusweb.site/dev.openfrontend.tourismusweb.site/$CLEANED_BRANCH_NAME" >> $GITHUB_ENV

            - name: Echo the target path
              run: echo $TARGET_PATH

#            - name: Cleanup
#              uses: cross-the-world/ssh-pipeline@master
#              with:
#                  host: ${{ secrets.DEPLOY_HOST }}
#                  user: ${{ secrets.DEPLOY_USERNAME }}
#                  port: ${{ secrets.DEPLOY_PORT }}
#                  key: ${{ secrets.DEPLOY_KEY }}
#                  script: rm -rf $TARGET_PATH
