name: Cleanup on branch delete

on: delete

jobs:
    cleanup:
        if: github.event.ref_type == 'branch'
        name: Cleanup on branch delete
        runs-on: ubuntu-latest
        steps:
            - name: Set environment variables based on branch
              env:
                GIT_BRANCH: ${{ github.event.ref }}
              run: |
                CLEANED_BRANCH_NAME=${GIT_BRANCH//\//-}
                echo "TARGET_PATH=/var/www/vhosts/openfrontend.tourismusweb.site/dev.openfrontend.tourismusweb.site/$CLEANED_BRANCH_NAME" >> $GITHUB_ENV

            - name: Remove files from server
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: rm -rf ${{ env.TARGET_PATH }}
