name: Build and Deploy

on:
    pull_request: ~
    push:
        branches:
          - '*'
        tags:
          - '*'

jobs:
    build_and_deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Set environment variables based on branch
              env:
                IS_MAIN_BRANCH: ${{ github.ref_name == 'main' }}
              run: |
                CLEANED_BRANCH_NAME=${GITHUB_REF_NAME//\//-}
                if ${IS_MAIN_BRANCH} == true; then
                  echo "BASE_URL=https://openfrontend.tourismusweb.site/" >> $GITHUB_ENV
                  echo "TARGET_PATH=/var/www/vhosts/openfrontend.tourismusweb.site/openfrontend.tourismusweb.site" >> $GITHUB_ENV
                else
                  echo "BASE_URL=https://dev.openfrontend.tourismusweb.site/$CLEANED_BRANCH_NAME/" >> $GITHUB_ENV
                  echo "TARGET_PATH=/var/www/vhosts/openfrontend.tourismusweb.site/dev.openfrontend.tourismusweb.site/$CLEANED_BRANCH_NAME" >> $GITHUB_ENV
                fi

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install JS dependencies
              run: yarn install

            - name: Build the OpenFrontend.Framework
              run: yarn dist-build

            - name: Build the docs
              run: yarn docs-build

            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: '_site/*'
                  target: ${{ env.TARGET_PATH }}
                  rm: true
                  strip_components: 1
