name: Build and Deploy

on:
    pull_request: ~
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    build_and_deploy:
        name: Build and Deploy
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: none

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install JS dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Install PHP the dependencies
              run: composer install -o --no-dev --no-interaction --no-suggest

            - name: Build the OpenFrontend.Framework
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Build the docs
              run: vendor/bin/sculpin generate --env=prod

            - name: Deploy
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: 'output_prod/*'
                  target: ${{ secrets.DEPLOY_TARGET_PATH }}
                  rm: true
                  strip_components: 1