name: PR

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  assign-pr:
    name: Assign PR
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Assign the PR
        uses: toshimaru/auto-author-assign@v1.4.0
